{
  "runOn": [
    {
      "minServerVersion": "4.3.1",
      "topology": [
        "replicaset",
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "data": [
    {
      "_id": 1,
      "x": 11
    }
  ],
  "tests": [
    {
      "description": "InsertMany succeeds with RetryableWriteError from server",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "insert"
          ],
          "errorCode": 112,
          "errorLabels": [
            "RetryableWriteError"
          ]
        }
      },
      "operation": {
        "name": "insertMany",
        "arguments": {
          "documents": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ],
          "options": {
            "ordered": true
          }
        }
      },
      "outcome": {
        "result": {
          "insertedIds": {
            "0": 2,
            "1": 3
          }
        },
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      }
    },
    {
      "description": "InsertMany fails if server does not return RetryableWriteError",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "insert"
          ],
          "errorCode": 11600,
          "errorLabels": []
        }
      },
      "operation": {
        "name": "insertMany",
        "arguments": {
          "documents": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ],
          "options": {
            "ordered": true
          }
        }
      },
      "outcome": {
        "error": true,
        "result": {
          "errorLabelsOmit": [
            "RetryableWriteError"
          ]
        },
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            }
          ]
        }
      }
    },
    {
      "description": "InsertMany succeeds after PrimarySteppedDown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "insert"
          ],
          "errorCode": 189,
          "errorLabels": [
            "RetryableWriteError"
          ]
        }
      },
      "operation": {
        "name": "insertMany",
        "arguments": {
          "documents": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ],
          "options": {
            "ordered": true
          }
        }
      },
      "outcome": {
        "result": {
          "insertedIds": {
            "0": 2,
            "1": 3
          }
        },
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      }
    },
    {
      "description": "InsertMany succeeds after WriteConcernError ShutdownInProgress",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "insert"
          ],
          "errorLabels": [
            "RetryableWriteError"
          ],
          "writeConcernError": {
            "code": 91,
            "errmsg": "Replication is being shut down"
          }
        }
      },
      "operation": {
        "name": "insertMany",
        "arguments": {
          "documents": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ],
          "options": {
            "ordered": true
          }
        }
      },
      "outcome": {
        "result": {
          "insertedIds": {
            "0": 2,
            "1": 3
          }
        },
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      }
    }
  ]
}
